apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-torch-inference
spec:
  rules:
    - host: serveml.tripabhi.io
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  simple-torch-inference
                port:
                  number: 80