apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: l5d-header-middleware
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "bert.traefik.local:80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: simple-torch-inference-bert-ingress-route
  namespace: sml
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`bert.traefik.local`)
    priority: 0
    middlewares:
    - name: l5d-header-middleware
    services:
    - kind: Service
      name: simple-torch-inference-bert
      port: 80
