apiVersion: v1
kind: Service
metadata:
  name: simple-torch-inference-bert
spec:
  type: LoadBalancer
  selector:
    app: simple-torch-inference-bert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9081